### ISSUE TITLE
Allow a list of directories for the "path" argument

### ISSUE THREAD

**Issue by pfmoore** [ofek/find-exe#3]
The "path" argument to the various functions is a string - I assume it has the same format as the `PATH` environment variable (`os.pathsep` separated directories to search). It might be useful to also allow a list of strings for cases where the set of paths to search is constructed programmatically.

Note: I've only just looked at this library for the first time - while I can imagine places I'd find this useful, I don't actually have a use case for this right now, so this is very much just a suggestion.

**Comment by ofek** [comment]
Good idea, thanks! I chose to add a new parameter for a better user experience e.g. passing a list would be odd for a parameter name that is not plural.

**Comment by ofek** [comment]
https://github.com/ofek/find-exe/releases/tag/v0.2.0

**Comment by pfmoore** [comment]
Nice! And while I have your attention, I noticed that `_get_executable_extensions` would fail if `$env:PATHEXT` contained lowercase items. It would be more robust to have

```
EXECUTABLE_EXTENSIONS = tuple(ext.upper() for ext in pathext.split(os.pathsep) if ext)
```

**Comment by ofek** [comment]
Thanks! Fixing https://github.com/ofek/find-exe/pull/5

**Comment by ofek** [comment]
https://github.com/ofek/find-exe/releases/tag/v0.2.1
